### ISSUE TITLE
PD_STATE is never set to "GENESIS" in a single cluster mode (KUBERNETES)

### ISSUE THREAD

**Issue by dnitsch** [pingidentity/pingidentity-devops-getting-started#150]
**Describe the bug**

When running pingdirectory in single cluster replication mode with 3 replicas the PD_STATE is never set to GENESIS on the SEED node and hence the userRoot ldif import is never run. 

Replication is initialised and enabled correctly across the single cluster, but the data is never ingested.

**To Reproduce**
using default set up and setting these additional values for the configmap for the statefulset

```yaml
  K8S_STATEFUL_SET_NAME: pingdirectory
  K8S_STATEFUL_SET_SERVICE_NAME: pingdirectory
  K8S_NUM_REPLICAS: "3"
  K8S_INCREMENT_PORTS: "false"
  ORCHESTRATION_TYPE: KUBERNETES
  REPLICATION_PORT: "8989"
  HTTPS_PORT: "1443"
  STARTUP_COMMAND: /opt/out/instance/bin/start-server
  MAX_HEAP_SIZE: 1024m
  LOCATION: eu-west-1
  VERBOSE: "false"
  PING_DEBUG: "true"
```

**Expected behavior**

when `03-build-run-plan.sh` hook is run the the PD_STATE to be set to `GENESIS` and hence run the import ldif section.

**Screenshots**
replication enabled and cluster correctly initialised 
![image](https://user-images.githubusercontent.com/6850870/99097341-681b2700-25cf-11eb-9266-295adfac2076.png)

**Environment:**

EKS using Docker build.
`FROM pingidentity/pingdirectory:8.1.0.0-alpine-java11-edge`

**Additional Info**
Add any other information about the problem here.
