### ISSUE TITLE
Cannot get container running at all 

### ISSUE THREAD

**Issue by makaveli0129** [pingidentity/pingidentity-devops-getting-started#339]
**Describe the bug**
When spinning up in minikube i get the following:
```
curl: (6) Could not resolve host: license.pingidentity.com
curl: (6) Could not resolve host: license.pingidentity.com
curl: (6) Could not resolve host: license.pingidentity.com
curl: (6) Could not resolve host: license.pingidentity.com
curl: (6) Could not resolve host: license.pingidentity.com
curl: (6) Could not resolve host: license.pingidentity.com
curl: (6) Could not resolve host: license.pingidentity.com
curl: (6) Could not resolve host: license.pingidentity.com
```
utilizing the following with the helm chart 
```
global:
  image:
    tag:
      2203
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
    #per https://devops.pingidentity.com/reference/faqs/#no-egress
    # MUTE_LICENSE_VERIFICATION: "true"
    # MOTD_URL: ""
    # SERVER_PROFILE_URL: ""
    PING_IDENTITY_DEVOPS_USER: "this stuff here"
    PING_IDENTITY_DEVOPS_KEYVOPS_KEY: actual-key-here

pingfederate-admin:
  enabled: true
  envs:
    # SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    # SERVER_PROFILE_PATH: getting-started/pingfederate

pingfederate-engine:
  enabled: true
  envs:
    # SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    # SERVER_PROFILE_PATH: getting-started/pingfederate
```
**Expected behavior**
Pods would spin up but they never actually come online. 
I had to comment SERVER_PROFILE_URL otherwise i would get a github error on unable to pull the profile

**Screenshots**

**Environment:**
 - Github Repo: pingidentity-devops,
 - Docker Container: pingfederate
 - Cloud Environment: Minikube

**Additional Info**
Running anything like 
```kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4```
and then shelling in and looking up DNS i get the following:
```
root@hello-node-6b89d599b9-vx5zn:/# nslookup license.pingidentity.com
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
license.pingidentity.com	canonical name = lb-lic-pingidentity-com-503992372.us-west-2.elb.amazonaws.com.
Name:	lb-lic-pingidentity-com-503992372.us-west-2.elb.amazonaws.com
Address: 52.11.234.202
Name:	lb-lic-pingidentity-com-503992372.us-west-2.elb.amazonaws.com
Address: 52.35.118.204

root@hello-node-6b89d599b9-vx5zn:/#
```

doing the same thing on the ping docker container i get the following
```
################################################################################
                Ping Identity DevOps Docker Image

       Version: pingfederate-alpine_3.15-al11-11.0.0-220105-dafe
   DevOps User: ##############
      Hostname: pf-pingfederate-admin-8694774f67-p9qmm
       Started: Wed Apr 13 23:28:43 UTC 2022
################################################################################
################################################################################
PingFederate:pf-pingfederate-admin-8694774f67-p9qmm:/opt
> nslookup license.pingidentity.com
Server:		10.96.0.10
Address:	10.96.0.10:53

license.pingidentity.com	canonical name = lb-lic-pingidentity-com-503992372.us-west-2.elb.amazonaws.com
Name:	lb-lic-pingidentity-com-503992372.us-west-2.elb.amazonaws.com
Address: 52.35.118.204
Name:	lb-lic-pingidentity-com-503992372.us-west-2.elb.amazonaws.com
Address: 52.11.234.202

** server can't find license.pingidentity.com: NXDOMAIN

PingFederate:pf-pingfederate-admin-8694774f67-p9qmm:/opt
```
relevant minikube data below:

```minikube start
😄  minikube v1.25.2 on Darwin 12.3.1
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m```
