### ISSUE TITLE
org.eclipse.jetty.server.handler.ContextHandler.pingfederate unavailable after startup of PingFederate Admin sever in Azure Kubernetes

### ISSUE THREAD

**Issue by tomdecock-savaco** [pingidentity/pingidentity-devops-getting-started#361]
**Environment**
PingFederate deployed in Azure Kubernetes Service using Helm Chart from ping-identiy-devops
- Enabled pingfederate-admin and pingfederate-engine as Statefulsets (clustered mode) with persistent storage for /opt/out (using storage class for Azure File Share) - Image tag **11.0.3-latest**
- Pods themselves are running OK, Services, Ingress created correctly, 
- /opt/out files get written in Persistent Volume / Azure File Share.
- Mounted existing product license for pingfederate using Kubernetes secret: licensing is OK (can be seen in log files)

With regard to the deployed Kubernetes resources, everything looks OK.

**Bug Description**
Trying to connect to the admin console of Pingfederate in the browser (https://_admin-server-host_:9999/pingfederate/app) returns:
> HTTP ERROR 404 Not Found
> URI: /pingfederate/app
> STATUS: 404
> MESSAGE: Not Found
> SERVLET: ReactServlet

**Logging**
opt/out/instance/log/server.log of pingfederate admin server shows warning after 'PingFederate started':
```
2022-06-10 07:15:39,536  INFO  [org.eclipse.jetty.server.Server] Started @153587ms
2022-06-10 07:15:39,541  INFO  [com.pingidentity.appserver.jetty.PingFederateInit] PingFederate started in 138s:712ms
2022-06-10 07:15:47,547  WARN  [org.eclipse.jetty.server.handler.ContextHandler.pingfederate] unavailable
org.apache.jasper.JasperException: Unable to set last modified date for file [/opt/out/instance/work/jetty-0_0_0_0-9999-pingfederate_war-_pingfederate-any-1628531342419048495/jsp/org/apache/jsp/WEB_002dINF/pages/main_jsp.java]
2022-06-10 07:15:47,549  WARN  [org.eclipse.jetty.server.HttpChannel] /pingfederate/app
javax.servlet.ServletException: org.apache.jasper.JasperException: Unable to set last modified date for file [/opt/out/instance/work/jetty-0_0_0_0-9999-pingfederate_war-_pingfederate-any-1628531342419048495/jsp/org/apache/jsp/WEB_002dINF/pages/main_jsp.java]
```

**Attached Log Files to this Issue**
Uploaded relevant Pingfederate log files (the only ones that were written to) - warning kan be seen in server.log of admin server
[issue-logs.zip](https://github.com/pingidentity/pingidentity-devops-getting-started/files/8877512/issue-logs.zip)

**Comment by tomdecock-savaco** [comment]
Uploaded additional console output of the following commands:
- helm upgrade --install $HELM_RELEASE_NAME pingidentity/ping-devops --version 0.9.2 --values pingfederate.yaml --namespace pingfederate
- kubectl get all --selector=app.kubernetes.io/instance=pf-hr --namespace=pingfederate
- kubectl logs statefulset.apps/pf-hr-pingfederate-admin --namespace=pingfederate

The last command shows the logs of the pod/container.
It seesms to go wrong in the following section:
----- Starting hook: /opt/staging/hooks/81-after-start-process.sh

Output of these 3 commands is shown in the attached/uploaded file:
[deployment-console-output.txt](https://github.com/pingidentity/pingidentity-devops-getting-started/files/8877730/deployment-console-output.txt)

**Comment by arnaudlacour** [comment]
Thanks for submitting this ticket with the console output log.
From looking at it, I would presume that the container user and group are not right for the `/opt/out` volume.
Maybe you could confirm what user id and group id the java process running PingFederate has and what the permissions are for the volume?

**Comment by tomdecock-savaco** [comment]
Hello Arnaud, 
The user is not explicitly changed as far as I know.  I am using the latest stable pingfederate image from https://hub.docker.com/r/pingidentity/pingfederate. The issue was reproduced with a fresh install using the helm chart from https://helm.pingidentity.com/. 

The opt/out volume is mounted with the _pingfederate.yaml_ file used as custom values file for the helm chart: 

```
  workload:
    type: StatefulSet 

    statefulSet:
      partition: 0

      persistentvolume:
        enabled: true
        volumes:
          out-dir:
            mountPath: /opt/out
            persistentVolumeClaim:
              accessModes:
              - ReadWriteMany
              storageClassName: pingfederate-storageclass
              resources:
                requests:
                  storage: 4Gi
```
The storageClass is using an Azure File Share:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingfederate-storageclass
provisioner: file.csi.azure.com
parameters:
  location: westeurope
  resourceGroup: VDWConnect-AKS-rg
  skuName: Standard_LRS
  storageAccount: vdwconnectakssa
reclaimPolicy: Retain
mountOptions:
- nouser_xattr
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

A Managed Identity linked to AKS is given permission to the Azure Storage Account for the file share.
I notice that the fileshares get created, and that the /opt/out files are written to the file share. 
So there everything looks OK.  We have been using similar storageclasses for other deployments in the same cluster without issues.

Regards,
Tom
