### ISSUE TITLE
would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false

### ISSUE THREAD

**Issue by gsustek** [pingidentity/pingidentity-devops-getting-started#444]
**Describe the bug**
a lots of warning while installing 
pingfederate-admin    2211              
pingfederate-engine   2211  
in openshift 4.11
**To Reproduce**
install ping federate on openshift 4.11

**Expected behavior**
no errors / warning

**Screenshots**
helm upgrade cust pingidentity/ping-devops --install --atomic --namespace=cust  -f ./pingfederate-helm
Release "cust" does not exist. Installing it now.
W1222 13:56:46.437744     422 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "pingfederate-admin" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pingfederate-admin" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pingfederate-admin" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pingfederate-admin" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W1222 13:56:46.442517     422 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (containers "wait-for-pingfederate-admin", "pingfederate-engine" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "wait-for-pingfederate-admin", "pingfederate-engine" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "wait-for-pingfederate-admin", "pingfederate-engine" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "wait-for-pingfederate-admin", "pingfederate-engine" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
NAME: cust

**Environment:**
 openshift 4.11

**Additional Info**

The k8s API for the Pod security policy has changed and it has been replaced by the Pod Security Admission, so it looks like we need something in addition now in the SCC definitions.

This is a discussion related to the operator changes that may be helpful for the operator changes: https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417

pingfederate-helm.values:

`pingfederate-admin:
  enabled: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    defaultDomain: apps.also.clusters.something.io
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: getting-started/pingfederate
pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: getting-started/pingfederate
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
global:
  workload:
    securityContext: null
  externalImage:
    pingtoolkit:
      securityContext: null`

**Comment by TechnoRoss** [comment]
thanks @gsustek for this report.  All of this is related to the deprecated Pod Security Policy which is removed in Kubernetes 1.25.  We have an internal ticket open for reviewing what changes need to be made in our charts in order to support the new Pod Security Admission framework moving forward.

**Comment by henryrecker-pingidentity** [comment]
@gsustek We plan on updating the chart in the next release to set defaults that prevent these warning messages.

For the time being, you can workaround this by adding the required fields to your values.

```
global:
  workload:
    securityContext:
      fsGroup: null
      runAsUser: null
      runAsGroup: 0
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  externalImage:
    pingtoolkit:
      securityContext:
        runAsUser: null
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsGroup: 0
        seccompProfile:
          type: RuntimeDefault
...
```

The null values are set to allow openshift to override them.
