### ISSUE TITLE
Docker Compose does not find Ping Access license

### ISSUE THREAD

**Issue by thatdc-reply** [pingidentity/pingidentity-devops-getting-started#486]
Hi, I am trying to deploy Ping Access with docker and then add a license layer, to provide the license to Access.
I am following [this guide](https://devops.pingidentity.com/how-to/profilesLayered/). I also forked [this repository](https://github.com/pingidentity/pingidentity-server-profiles/tree/master) as suggested in the guide.

In my fork I added the following folder structure:
```
layered_profiles
  license
    pingaccess
      instance
        conf
          pingaccess.lic
```

Here is the `docker-compose.yml` file I am using:

```
services:
  pingaccess:
    image: pingidentity/pingaccess:latest
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
    environment:
      # License profile
      - SERVER_PROFILE_URL=https://github.com/thatdc-reply/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=layered_profiles/license/pingaccess
      - SERVER_PROFILE_PARENT=GETTING_STARTED
      
      # Base Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/thatdc-reply/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingaccess
      
      # Initial credentials, not sure this is actually necessary here
      - PA_ADMIN_PASSWORD_INITIAL=2Access
      - PING_IDENTITY_PASSWORD=2FederateM0re

    ports:
      - "3000:3000"
      - "9000:9000"
    networks:
      - pingnet
    volumes:
      - pingaccess-out:/opt/out

networks:
  pingnet:

volumes:
  pingaccess-out:
```

When I run `sudo docker-compose up`, the script runs fine for a while, but then this error shows up:

```
pingaccess_1  | ----- Starting hook: /opt/staging/hooks/83-change-password.sh
pingaccess_1  | CONTAINER FAILURE: ERROR: No valid administrator password found - Check variables PING_IDENTITY_PASSWORD and PA_ADMIN_PASSWORD_INITIAL
pingaccess_1  | PingAccess exiting
pingaccess_1  | CONTAINER FAILURE: Error running 83-change-password.sh
pingaccess_1  | 
pingaccess_1  | /opt/out/instance/log/pingaccess.log:  2023-05-09T10:54:22,695 ERROR [gSO2twlE22ycUuz_fUa0Gg] com.pingidentity.pa.license.LicenseInterceptor - Cannot load the license file.
pingaccess_1  | /opt/out/instance/log/pingaccess.log:  com.pingidentity.pa.license.manager.LicenseException: There was a problem trying to read the license file.
[ ... ]
pingaccess_1  | /opt/out/instance/log/pingaccess.log:  Caused by: java.nio.file.NoSuchFileException: /opt/out/instance/conf/pingaccess.lic
```

As far as I understand, the license profile is not correctly pushing the license to the correct directory of the image.
What am I doing wrong here?
