### ISSUE TITLE
incorrect PingAccess version loaded from what was specified as 'tag'.

### ISSUE THREAD

**Issue by aalmero** [pingidentity/pingidentity-devops-getting-started#576]
**Describe the bug**
Incorrect PingAccess version loaded in the k8s container.

**To Reproduce**
everything.yaml
```
...
pingaccess-admin:
  enabled: true
  privateCert:
    generate: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingaccess
    SERVER_PROFILE_UPDATE: "true"
  container:
    waitFor:
      pingfederate-engine:
        service: https
        timeoutSeconds: 300
  image:
    tag: "2405-7.3.4"      
  secretVolumes:
    pingaccess-license:
      items:
        pingaccess.lic: /opt/in/instance/conf/pingaccess.lic 
...
```

**Expected behavior**
Version information from the console should show 7.3.4.

**Actual behaviour**
Version information from the console should show 8.2.0.2

**Environment:**
 - Kind, Docker on MacOS

**Additional Info**
I added SERVER_PROFILE_UPDATE: "true" as initially it was not loading the provided license.
The license shows expired/invalid as the license mounted was for 7.3.x

POD logs shows correct version
################################################################################
                Ping Identity DevOps Docker Image

       Product: PingAccess
       Version: 7.3.4-alpine_3.20.0-al11
 
The PingFederate seems to work as expected.
```
...
pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingfederate
  image:
    tag: "2403-11.3.5"       
  secretVolumes:
    pingfederate-license:
      items:
        pingfederate.lic: /opt/in/instance/server/default/conf/pingfederate.lic
...
```

**Comment by henryrecker-pingidentity** [comment]
@aalmero Is the Docker image tag that is set in the resulting k8s configuration incorrect? You can run `helm template` to see the generated yaml that gets sent to kubernetes. I ran a `helm template` with your PingAccess yaml and the image tag is set correctly.
```
# Source: ping-devops/templates/pingaccess-admin/workload.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pingaccess-admin
    helm.sh/chart: ping-devops-0.11.2
  name: test-pingaccess-admin
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: pingaccess-admin
  serviceName: test-pingaccess-admin-cluster
  template:
    ...
    spec:
      affinity: {}
      containers:
      - args: null
        envFrom:
          ...
        image: pingidentity/pingaccess:2405-7.3.4
        ...
```

**Comment by aalmero** [comment]
```
        image: pingidentity/pingaccess:2405-7.3.4
        imagePullPolicy: Always
        lifecycle: {}
```
Seem I had the same as above.  I also tried to check if the tag exist and would default to 'latest' if not exist but I don't think it is the case. Is there like and upgrade that is happening? I will try re-creating the cluster to see if there some sort of caching.

Thanks for the feedback.

**Comment by aalmero** [comment]
I completely wipe the cluster and re-run and was able to load the correct version.   I will run another test to find out why it wasn't working after deploying the default '2412' release.

**Comment by aalmero** [comment]
After deploying specific version(7.3.4), I did helm uninstall and then loaded with default release(2412) and again the PA version didn't get replaced. However the PF is working fine switching between versions without any issues. What I find interesting is that when I listed the images loaded(kubectl get nodes ping-control-plane -o yaml) there's 2 images loaded for PA.
```
    - docker.io/pingidentity/pingfederate@sha256:b991e9ed843cc073e4e3c6add422a64e097b69ba3a3aacb3337acf54e99d9a37
    - docker.io/pingidentity/pingfederate:2412
    sizeBytes: 622025132
  - names:
    - docker.io/pingidentity/pingaccess@sha256:9477c2d8c1b5ac122e6ed889ba7b0ed04631d04a62d6c3ebf96c1fea9961f399
    - docker.io/pingidentity/pingaccess:2412
    sizeBytes: 252114378
  - names:
    - docker.io/pingidentity/pingaccess@sha256:c5c132cf74ff2a6bb45acafb54a20c665b69249b229466143dc31b2033c44147
    - docker.io/pingidentity/pingaccess:2405-7.3.4
    sizeBytes: 241348902
  - names:
    - docker.io/pingidentity/pingtoolkit@sha256:8652cea75260b033db37aa2dc2e0212b90374b64fb2adf9346d6e2f6293b5709
    - docker.io/pingidentity/pingtoolkit:2412
    sizeBytes: 163351727

```

**Comment by PingDavidR** [comment]
Chiming in on this discussion as well; when you run the helm installation, a persistent volume & persistent volume claim is created for the PingAccess admin console pod.  When you run `helm uninstall`, this PVC is not removed, and I am pretty sure this is where the persistence of the PA version is being created.

> NAME                              STATUS   VOLUME                                     
out-dir-demo-pingaccess-admin-0   Bound    pvc-732f4170-3826-4633-bb6d-283a861f9443  ... 
out-dir-demo-pingdirectory-0      Bound    pvc-d6d895de-78fd-42ed-935f-76d9f4d8f0b0  ...

**Comment by aalmero** [comment]
I run helm template to see that chart and it shows that for PA admin it is using the workload of type statefulSet which is defined below.  My recent deployment test now causes a clustering issue due to a version conflict between the admin and the engine.  Is there a reason why the workload type is 'statefulSet'?
```
...
 statefulSet:
   partition: 0
   persistentvolume:
        enabled: true
        volumes:
          out-dir:
            mountPath: /opt/out
            persistentVolumeClaim:
              accessModes:
              - ReadWriteOnce
              storageClassName:
              resources:
                requests:
                  storage: 4Gi
...
```
